version: '3.7'

services:
  mstweb:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=dh.bitc.ru
    volumes:
      - it_data:/usr/src/app/
    ports:
      - 8021:8000
    networks:
      - qre_net
networks:
  qre_net:
    external: true
    name: qrestimatenet
volumes:
  mst_data:
