version: '3.7'

services:
  snestrotech:
    build: ./
    container_name: con-nesto-tech-2021
    command: gunicorn --bind 0.0.0.0:8011 monstability.wsgi:application
    environment:
      - DBPASSWORD=P@ssw0rd
      - DBHOST=qre_db
      - DBPORT=5432
      - DJANGO_DEBUG=false
    volumes:
      - .:/usr/src/app/
      #- static_volume:/usr/src/app/monstability/static
      - npm_static_volume:/vol/web/static
    expose:
      - 8011
    networks:
      - npm_net
networks:
  npm_net:
    external: true
    name: npmnet
#volumes:
#  static_volume:
#    external: true
#    name: statiic_nestrotech
volumes:
  npm_static_volume:
    external: true
