version: '3.7'

services:
  mstweb:
    build: ./
    command: python monstability/manage.py runserver 0.0.0.0:8000
    environment:
      - DBPASSWORD=P@ssw0rd
      - DBHOST=qre_db
      - DBPORT=5432
    volumes:
      - .:/usr/src/app/
    ports:
      - 8021:8000
    networks:
      - qre_net
networks:
  qre_net:
    external: true
    name: qrestimatenet
