version: '3.7'

services:
  itweb:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8021:8000
    networks:
      - qre_net
networks:
  qre_net:
    external: true
    name: qrestimatenet

