version: '3.7'

services:
  nestrotech-www:
    build: ./
    container_name: nesto_tech_2021
    command: gunicorn --bind 0.0.0.0:8000 monstability.wsgi:application
    environment:
      - DBPASSWORD=P@ssw0rd
      - DBHOST=qre_db
      - DBPORT=5432
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/monstability/static
    expose:
      - 8000
    networks:
      - qre_net
networks:
  qre_net:
    external: true
    name: qrestimatenet
volumes:
  static_volume:
    external: true
    name: static_nestrotech
