# Generated by Django 3.2.7 on 2021-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0011_auto_20210927_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasenodes',
            name='step',
            field=models.IntegerField(default=1, help_text='Шаг теста', verbose_name='step'),
        ),
    ]
